apply plugin: 'com.android.application'

android {
    compileSdkVersion 34
    defaultConfig {
        applicationId "co.qrail.iteractive.map"
        minSdkVersion 26
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    namespace "qrail.com.interactivemap"
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    
    // For appcompat (provides ActionBar, AppCompatActivity, etc.)
    implementation 'androidx.appcompat:appcompat:1.7.0-alpha03'
    
    // For ConstraintLayout
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0-alpha13'
    
    // Core Android dependencies
    implementation 'androidx.core:core:1.12.0'
    implementation 'androidx.activity:activity:1.8.2'
    
    // Testing dependencies
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}